apiVersion: v1
kind: Namespace
metadata:
  name: finance
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data
  namespace: finance
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual-budget
  namespace: finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actual-budget
  template:
    metadata:
      labels:
        app: actual-budget
    spec:
      containers:
      - name: actual-budget
        image: actualbudget/actual-server:latest
        ports:
        - containerPort: 5006
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: actual-data
---
apiVersion: v1
kind: Service
metadata:
  name: actual-budget
  namespace: finance
spec:
  selector:
    app: actual-budget
  ports:
  - port: 5006
    targetPort: 5006
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: actual-budget-tailscale
  namespace: finance
  annotations:
    tailscale.com/expose: "true"
spec:
  type: LoadBalancer
  selector:
    app: actual-budget
  ports:
  - port: 5006
    targetPort: 5006
    protocol: TCP