apiVersion: v1
kind: Secret
metadata:
    name: mango-secret
    namespace: mango
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:cfvb2gto5+QaTciip6iPGOSIPHOLpuPT2Z+d8Gi31c4pvfuM0H5mXauYEXWYwg==,iv:iIs5ZZ2f1oQ/GjqUc2f7KNSmNQ0ggQp+BLTaEOaQR+8=,tag:bJkI7x+ZTeiQQQNgDVLbFA==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:tBidiKiRdsY7Or1+A8ZSNyr0WbIIWNBzhR7LQFZ/xzk=,iv:D1JClDg7aM7+uAY1596+dDzyVLgHNLcFLu6Ob406v7g=,tag:5aNctupiGKhCcLfhsYjAeQ==,type:str]
    BETTER_AUTH_BASE_URL: ENC[AES256_GCM,data:m7e8C7eBy/HNBT3S+DNrrFkaiNGOqvHZRDrV4RVg231PIoo343UJ/7h/PdXQZ8ImwpCxBHM=,iv:tBGhj8mVxwugB6HLOdWQ+AgVTB9byLwOuDRwddelQo8=,tag:xcAXDjTti7w5R2IC26kkOA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:3SWKRA==,iv:sZhF5NZvYQ1q35U/xT15C8JDwMFWbGHwt2AOo6e5zyI=,tag:zS7L1pNkfEU6uXeql79VDQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:hUkvRGTexpc=,iv:XKmxuP+ZxiIPYH6BpDpbtFZSdKMbwaA1N95DuDWrnOQ=,tag:D9wCEiy0CWPjRoRpupkpyQ==,type:str]
sops:
    age:
        - recipient: age1cdptwtsh43266j2lm5w9yt44xz8nvscw3srvqgsec26md5lmhemsm4xqka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bFU4ZDlpZE5JNFlKb3d2
            MlRIeEUzYngvdkFpRkdSUVRrRnRGVEN0bkhZCmxOaFM3TG9kMlNDUEl1clgwbFBR
            NG04UHZmZThmRmZ1a0R5eGVBUWdsMFUKLS0tIFJKUVhIUEdwdGJsQVdjWnRWTWdy
            V1MrVERRNzBZVkVGK0czbHBpZklEZEUK/PcM3Qwke1AefTtKTUksx7QXRNbBnkOJ
            nOihpR+ZGs9JNYY9AfYg2qh2JQTNJyIfQ50v9jp3hzjoKUn0+x7FdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T10:58:38Z"
    mac: ENC[AES256_GCM,data:yUj9j8EQn4tQqgG00o5EFpMUDyVobbNlHuKSjZHBJe9Htqujmoxd9/65DxUTEOHsVSaAxDpFFY+HJSBzbu8MV4JdVeVpWPMUpjAFHKLqDM+KcQ5SMK2Jky7AF1Ob0vN1W/6GyylcTdLaIKSs/A2Kidb78XfBupDQy92vQhXH31E=,iv:OggXze5nlfwEMKXppBYgyCGsKlWJiRd/SrlZeUR2/IQ=,tag:lqz0XyUGVT6LvoGlGskJig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
