apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"operator","namespace":"tailscale"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"operator"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"operator"}},"spec":{"containers":[{"env":[{"name":"OPERATOR_INITIAL_TAGS","value":"tag:k8s-operator"},{"name":"OPERATOR_HOSTNAME","value":"tailscale-operator"},{"name":"OPERATOR_SECRET","value":"operator"},{"name":"OPERATOR_LOGGING","value":"info"},{"name":"OPERATOR_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"OPERATOR_LOGIN_SERVER","value":null},{"name":"OPERATOR_INGRESS_CLASS_NAME","value":"tailscale"},{"name":"CLIENT_ID_FILE","value":"/oauth/client_id"},{"name":"CLIENT_SECRET_FILE","value":"/oauth/client_secret"},{"name":"PROXY_IMAGE","value":"tailscale/tailscale:unstable"},{"name":"PROXY_TAGS","value":"tag:k8s"},{"name":"APISERVER_PROXY","value":"false"},{"name":"PROXY_FIREWALL_MODE","value":"auto"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_UID","valueFrom":{"fieldRef":{"fieldPath":"metadata.uid"}}}],"image":"tailscale/k8s-operator:unstable","imagePullPolicy":"Always","name":"operator","volumeMounts":[{"mountPath":"/oauth","name":"oauth","readOnly":true}]}],"nodeSelector":{"kubernetes.io/os":"linux"},"serviceAccountName":"operator","volumes":[{"name":"oauth","secret":{"secretName":"operator-oauth"}}]}}}}
  creationTimestamp: "2025-10-04T08:28:07Z"
  generation: 1
  name: operator
  namespace: tailscale
  resourceVersion: "26762"
  uid: 29398301-9c39-41ad-97d5-1b7f469c09f8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
      - env:
        - name: OPERATOR_INITIAL_TAGS
          value: tag:k8s-operator
        - name: OPERATOR_HOSTNAME
          value: tailscale-operator
        - name: OPERATOR_SECRET
          value: operator
        - name: OPERATOR_LOGGING
          value: info
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OPERATOR_LOGIN_SERVER
        - name: OPERATOR_INGRESS_CLASS_NAME
          value: tailscale
        - name: CLIENT_ID_FILE
          value: /oauth/client_id
        - name: CLIENT_SECRET_FILE
          value: /oauth/client_secret
        - name: PROXY_IMAGE
          value: tailscale/tailscale:unstable
        - name: PROXY_TAGS
          value: tag:k8s
        - name: APISERVER_PROXY
          value: "false"
        - name: PROXY_FIREWALL_MODE
          value: auto
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        image: tailscale/k8s-operator:unstable
        imagePullPolicy: Always
        name: operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /oauth
          name: oauth
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: operator
      serviceAccountName: operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: oauth
        secret:
          defaultMode: 420
          secretName: operator-oauth
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-04T08:45:32Z"
    lastUpdateTime: "2025-10-04T08:45:34Z"
    message: ReplicaSet "operator-5d9d5bc4d8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-10-04T10:45:12Z"
    lastUpdateTime: "2025-10-04T10:45:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
