apiVersion: batch/v1
kind: CronJob
metadata:
  name: cache-tester
  namespace: aucra
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: cache-tester
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cache-tester
            image: docker.io/aucra/cache-tester:test
            imagePullPolicy: Always
            env:
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: aucra-secret
                  key: ANTHROPIC_API_KEY
            - name: SSP_DB_URL
              valueFrom:
                secretKeyRef:
                  name: aucra-secret
                  key: SSP_DATABASE_URL
            - name: DSP_DB_URL
              valueFrom:
                secretKeyRef:
                  name: aucra-secret
                  key: DSP_DATABASE_URL
            - name: PROVIDER
              value: "claude"
            args:
            - --provider
            - "claude"
            - --urls
            - "https://redditcollegeresults.com"
            - --wait
            - "3"
