apiVersion: v1
kind: Secret
metadata:
    name: aucra-secret
    namespace: aucra
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:PEPosRWJtnqJcF9jujypa5Hqasu07x17zA6vQDhY/hyQf6BfzNVYhHAQHVjjuwZcMMCW4wE3AMr2U/pE7p1Fm95SgU9PwXRbhwUItwe4Pox5f8amY4Q=,iv:PzIusqu6k6stQ3rLmtxlww3+ZNaAAm8LZ047XXKGzhA=,tag:IF3/6c8Othk8tZA3tbMKwg==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:u71wmP7KtEwilhNqlXAFNcdOlAeg+RegqktxYSfGCes=,iv:SvRza7ptl1cvFrpFRlguPrPyCikH6hZIzyLDUg3eQvI=,tag:F/roXABd8/7CvOMhsLQWcw==,type:str]
    BETTER_AUTH_BASE_URL: ENC[AES256_GCM,data:AKqkNHY3zeEE4snlCoeGnl8dS4xuB4jVmhC10ybVkmbZJqcJRg17AqSLWvp4SoZkxD5sPfs=,iv:a0tUSDUWUboLItjza4jLQDShvqp7SjXY8LdD3LiykHU=,tag:ayLnAi/fOzVizOsOdkz4jQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Al0Yiw==,iv:OMPWhXAX9+a5OGELH7yie/TLYZDLiH5VaW4yY2L0f5w=,tag:12x6YH9XVKO88rIfTuJe6A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:DUlChiiS/8RRehLTgNgAGyeyEJzwWqwJ3RPYHTHtO4JAvXpyQlXC68RoGFYlb35M,iv:JbESNpTTo/ZyS3yY7TpV95ddKcjdLd8XW/bu6hfglG0=,tag:AL6ChZJ/gXpzhYwMXtgC2g==,type:str]
    ADMIN_KEY: ENC[AES256_GCM,data:t+nUo7L08/TCaBFHyCDE1N7sSVrM+UFlMA/ejt73tsf8RUAewa4QgIjM3bLHmkMEny3En8SByvnRaA9oPBosCQ==,iv:W6acs4X7umUGCF3S5dr7RX/6/dOTsXd1R0sPDfc2qds=,tag:p+LGmM0oG8bgwyH+txiSfw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:iiOphe97aTYKhUNdf4ec6a45Z1Ux/OkdTYcDjxIcfU3Wbg/z54DReCMyNMHH/MjOri7puTZ936OF5ZRtPt6HGQ==,iv:+nagykWzsfqxTHcTsuWMHVcdEqz/maDjWmL5D79ANmo=,tag:+3X9/eLkieckALYnlzgNOA==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:DY0qRTa5ZsxU1DrswMiDexOaJeChMNNtS1pJdf/YxQ1jPVqfLp6NsPtVJVWxM4k4A55dxAYPFizqY+/qxQyjU8e2UrqKCai+,iv:0qiwR4y7t/YZATdEgw867+JHuP/zhn3wa5hhBZ6bFxk=,tag:l5Tj3zLP3kf/C2D9M9+ZEg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:Iail8vRcp1HfMmy6PHH1lPKNdF3gtkwxBXsgq7YZczg5/U0=,iv:BFIMZtNHDv7ZIAOEW9cwcNfbQzYNQJk8j5Hb723n+eg=,tag:i5JfJGdq7DlYifhW+scInQ==,type:str]
    WHITELISTED_EMAILS: ENC[AES256_GCM,data:XvyfAh5RXCSolB/+XHFJShEwSCx/I8CxKS9ATTptNSq0UA/cW4mqlXmRxQ==,iv:+76QSsxnxaDXzNT6CMvBFkDNqkFaYZSg+DaJOSW/foY=,tag:lLCSptY6DO9ziGzd1O7RcA==,type:str]
    FRONTEND_URL: ENC[AES256_GCM,data:uCfKaarXQAmTBh05wZTiIEO6QbMVMc7e/4lQTm26nAKpkn9u1bJyz5aZNq4=,iv:68T9DKp8MbXD375hmezFJCJWb+fqj6zldDjwiEAY2WA=,tag:qq2Ono0t1R8GNHS+KG+h5w==,type:str]
sops:
    age:
        - recipient: age1cdptwtsh43266j2lm5w9yt44xz8nvscw3srvqgsec26md5lmhemsm4xqka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YzBudkMydnZ2VHNFUm4v
            VWZ4NWg4UkZtSGdFQ2EyYk9peW9wQjZvV3lnClVEbk9tVUlBRnlQcEErVitxTkVu
            VkpYb2xkZG85aUdQZkI5dmRvNXV2VFEKLS0tIGN5MFhVWEYrck8yT1JicmhLVmhx
            NkdxWFhFaE1pL1p1ejIrUE5xUzdEMzgKwAfILHNb20OoWnFUs9Njc9dcKBj1qp6R
            /6hEfVRUrvzs3TFPPJsmfkFIFaQRUjGVhLjfvPBZWsVIagm5pqOeBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T01:10:26Z"
    mac: ENC[AES256_GCM,data:lAqShvW9IXHwt8dqx38SGdwjMtxdARtxvC14cGN+ezvXYbv9KPTeAnTVLExW8tgi3Yy/Pj7UNwZR5xmPCgChjw3cqPfCQEt/0JHdU13K5S9UkmuNpn40rA95yWyrDv/U9HPZ1uw8u4/mHWVsYfi/GxlfcJyy0J/JxWbh3s9JJeU=,iv:W6vTBT+nof0Je6zYeMF8HGvuLwi0bPtWsI8fmOOdAdc=,tag:VG5vRZnvUuzsO+0kn4nLJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
