apiVersion: v1
kind: Secret
metadata:
    name: aucra-secret
    namespace: aucra
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:kWR8XRcHyzk7f2w2pmqRjO6XdR/SBsvum9Kh5V50xA==,iv:QR1cYuKnIkj3WRvgX6mZIMGcq27vbM8viXoQTuBtazg=,tag:jSHsaRiHBuMAxALvxcXLoA==,type:str]
    BETTER_AUTH_BASE_URL: ENC[AES256_GCM,data:7OHhMkgkgUrOu+58TgrBtUmF0TEEbQYt30HcgEv+lrNFtHiIUsUXShjdrUjqnIzuDhXwXPM=,iv:8JUl/0/MV1wLQ+Vr/m4kLEZ8ea3FM570d7cKdjPpm/s=,tag:yDTtkHfqb7HYH/YofeyXHQ==,type:str]
    DSP_DATABASE_URL: ENC[AES256_GCM,data:p093pHMTUKy4zloPtUTiA7Ulmvx2vAxiJ6RM/+u9jqHTCiJflIdoagvzJC0O4uxIUYJaUwwzUucemCHTF2JfKsXSabZ8xKjskicCMS3DiTD69A2oVe0j0ydDuH8rj1cL,iv:2NEuc7KMbO6sR0aOF4rmFMR14+7QhMFYmVIy6vi1Z2Q=,tag:ckHDReAYeKSBDDHAqFSmFw==,type:str]
    SSP_DATABASE_URL: ENC[AES256_GCM,data:2HYzfLxkn9cjl+0RkL6P5ZFvLgDI2Xc/8jReqip64ECv3KJ/xixBbNpLxvvXwmEZ5GisM195bLrrwql/SYvYJTkY5Er09Y5d8sR9vRJEEHe3dD9JcCxSkPOTmfgeI0ik,iv:W7SQF6A2xcZUvmcSXawIRR1UkrinT5iNTgeANcYiYjg=,tag:Y+e62Tx/thqf4d5c1WZi7w==,type:str]
    ADMIN_KEY: ENC[AES256_GCM,data:OzK7CDvmRkRX6ri0y6wB+2iroBI5YmM055EB79JlyJd/6QeqX45GU8uGQFgJ3NTIrb05kNoAnrFV1ypGhXk/zg==,iv:lJkL+P+g1rox8jNgqfJRfFSj8HOb1R88M9vv/5Rn0To=,tag:Z7yuCOi6fzBGwca8PtTcXA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:dBeFSW3UZcnDYtJ/YRvC/mndOQfxIvWiBJtJ3H0w7mKDWQJqTwnz/LMpbKRbAnBnWrh+1xfueOmx8jO4bPR0TA==,iv:U5elHPu4+utpGkt0kXTVGaONYE0xoMlkIc2fH61i3j0=,tag:r1D8AcS0wx6lJcNXOfJM4g==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:1Ll3ESr4qxP1W4dkR5YjJ1RSHB+mTgLomcLEiaQhQRaN0qRYEQvXbIBZ3VfvzZ0lAT+sXBcGHK7tXC5sSE9PAX7OwsXVDUq5,iv:2TUIqbVdj+0EJNwMon9FI0AxBeVfrL3/cRhJFdzLWcg=,tag:6qoLD2+vBFjnaTb4WevCfA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:ZJp8yzrCmbAeFtflnosk56oQLBBXxosNAVJkPo7Pp+p7JEE=,iv:5Pjygh+3SuD79d02cF9ykg0VcFBjQ/XUIULZew1LUaQ=,tag:qLHx1zSDxYNL7ybiFpo4NA==,type:str]
    WHITELISTED_EMAILS: ENC[AES256_GCM,data:H4QR/JSOiZMECqcM7HnHN2TPVa/xs0Szs4xcMTw7KnMY/cYpitkkAsNPdg==,iv:2B3LrLshNviW60t/5xmgwSJYjV8RtHeDK2QsanW97x0=,tag:6EoLpXM0liVFQtuTKy0x7w==,type:str]
    FRONTEND_URL: ENC[AES256_GCM,data:zOeTxrVGpDDkXXHCerz4sSbYOLTlGWSQ3/5dyQkQiccEnxVaeSjTr93LMxk=,iv:PZjkT8z+K/GCN0n5xZFvA0GhNXW553IcJUYvEjN4AI0=,tag:OC3dlYckNPY9UCPxMo0ywA==,type:str]
    DSP_ID: ENC[AES256_GCM,data:aogmtCk8YyPop80H1ibDFMDrqH2Gq3YIYEswVzYZ1MULOpZM,iv:jbnWPDUKim4UTugw/AsdsuJG0NLB7NiHVTZgS+AV+S4=,tag:rH0BSGx3G/tChBSElLbicg==,type:str]
    DSP_NAME: ENC[AES256_GCM,data:37s6iXE=,iv:I+F3eHFDfE9rL5zQ/toR7sBkaFTcVodj14L2wlONxT8=,tag:8hKsPa8sFVQiENb4zRSAGg==,type:str]
    DSP_BID_ENDPOINT: ENC[AES256_GCM,data:a/h54OA7uYQTgSzTKOmgJ1xpg3MEiZnawgVYPTlHpMvuoR/j49o/y2pKYw==,iv:2VFbvxEEWCnLxwWyTBB2gbH/0V96NihltLidpXI5QSE=,tag:ipjrqr2MszNNUTJ8esYXZg==,type:str]
    DSP_API_SECRET: ENC[AES256_GCM,data:vO2pQ5Uhg9IG8Zi2ytMPdzzNEsAFHDc0p8Ynh8IApgPNGxD0rzsxzI0vVeALn1m77wZpxqKvLeCUOVWL383m6Q==,iv:6uEilRFOAcwZHYv8PH1sa12MvYPJ47OITj5AH4+c1OM=,tag:L0LQoYGNDo/tdVyg4GyyUg==,type:str]
    JWT_ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:nJjEZZlzVeLX1y975gElsNoUdje0U8cUyQo9N0oCJyT8jUAQIO11MupQop8=,iv:NMLZGFzlzrq/gUCfECebERUaOE9h833a1KiwqlUfnEo=,tag:es1P968BWjP/ZJ+pgc56bQ==,type:str]
    JWT_REFRESH_TOKEN_SECRET: ENC[AES256_GCM,data:eLvGpaRg6ayDgmBAZZixiPHs3i1Dg+A5t3Y2TyYRxpTWb7I7JGYjriNLTSk=,iv:d2+s2mNxw0qpDHJeYnYoM9GKESflbOZgaf6FseDFuQ8=,tag:D7I293uzlCdCjqZDOWOXtQ==,type:str]
    JWTAccessTTL: ENC[AES256_GCM,data:NFoh,iv:aUM5vwt6MFAYXqvjjHbyHWdLFuWO8CFWbazUdC/Y+b4=,tag:4bay3JmSLtZpoAejptWsfQ==,type:str]
    JWTRefreshTTL: ENC[AES256_GCM,data:8TIalQ==,iv:DvUAeVvDLARni0xXmjwhsUtLVcH6W/AhVKqYTnN+6D0=,tag:UZQ9xge+4tOtsObRICOR0A==,type:str]
sops:
    age:
        - recipient: age1cdptwtsh43266j2lm5w9yt44xz8nvscw3srvqgsec26md5lmhemsm4xqka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVFRZUlQvUDc4UjZtUnk3
            OXhzcmprM2Q5cnZrZzlVM3laRjRORi9hK2h3CjJKcFlLbWRnTFVjaVpPcVl4MXBI
            dnYycDBsTlBReWNQL0ozaDlHeU5jNUUKLS0tIGV4UUcrY0VKVDZ6UXRSblZKanJu
            VEd3SXN0ZldJL1JOYmlQeDg0T3hZOTgKo52YUhlbyxV+1UIEfPT8utG9h45fa5hb
            DfyBTOc4DMNbxNFYqH28hrCiiTMsV7XDqYOpPwTXSbHKW7eCoYh6fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T16:11:31Z"
    mac: ENC[AES256_GCM,data:za/r5U7xxgyqb/Rdh0tnv0IN5oJkjju5Yw71OXdrMByiGYHvT/RU+W4k9gM7CVidMxHtMse2h7EHDR+5XZvSK6QWIvZXlpKqjEN1x3XhK0fJ7nj8lwvs/2o+jHfsH+i9m4ccAqPg4HuQ2UfsvTHNX1bJbNzPEmir+kXpUUT3uXI=,iv:Dn6Owj4XU+aXtqkzht96rSkniQ1eERKyqf5vB1foViU=,tag:1YwHGPesPE8rWxNxTPPluA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
