apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: true
  targetNamespace: tailscale
  valuesFrom:
  - kind: Secret
    name: tailscale-operator-oauth
    valuesKey: clientId
    targetPath: oauth.clientId
  - kind: Secret
    name: tailscale-operator-oauth
    valuesKey: clientSecret
    targetPath: oauth.clientSecret
