apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: operator
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: operator
        image: tailscale/k8s-operator:unstable
        imagePullPolicy: Always
        env:
        - name: OPERATOR_INITIAL_TAGS
          value: tag:k8s-operator
        - name: OPERATOR_HOSTNAME
          value: tailscale-operator
        - name: OPERATOR_SECRET
          value: operator
        - name: OPERATOR_LOGGING
          value: info
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_INGRESS_CLASS_NAME
          value: tailscale
        - name: CLIENT_ID_FILE
          value: /oauth/client_id
        - name: CLIENT_SECRET_FILE
          value: /oauth/client_secret
        - name: PROXY_IMAGE
          value: tailscale/tailscale:unstable
        - name: PROXY_TAGS
          value: tag:k8s
        - name: APISERVER_PROXY
          value: "false"
        - name: PROXY_FIREWALL_MODE
          value: auto
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - name: oauth
          mountPath: /oauth
          readOnly: true
      volumes:
      - name: oauth
        secret:
          secretName: operator-oauth
